#include "stdafx.h"
#include "KeyUtils.h"

#include "KeyboardKeysState.h"


namespace Dx
{
  std::unordered_set<KeyboardKey> getKeys(const KeyboardKeysState& i_state)
  {
    std::unordered_set<KeyboardKey> actions;

    if (i_state.Back) actions.insert(KeyboardKey::Back);
    if (i_state.Tab) actions.insert(KeyboardKey::Tab);
    if (i_state.Enter) actions.insert(KeyboardKey::Enter);
    if (i_state.Pause) actions.insert(KeyboardKey::Pause);
    if (i_state.CapsLock) actions.insert(KeyboardKey::CapsLock);
    if (i_state.Kana) actions.insert(KeyboardKey::Kana);
    if (i_state.Escape) actions.insert(KeyboardKey::Escape);
    if (i_state.ImeConvert) actions.insert(KeyboardKey::ImeConvert);
    if (i_state.ImeNoConvert) actions.insert(KeyboardKey::ImeNoConvert);
    if (i_state.Space) actions.insert(KeyboardKey::Space);
    if (i_state.PageUp) actions.insert(KeyboardKey::PageUp);
    if (i_state.PageDown) actions.insert(KeyboardKey::PageDown);
    if (i_state.End) actions.insert(KeyboardKey::End);
    if (i_state.Home) actions.insert(KeyboardKey::Home);
    if (i_state.Left) actions.insert(KeyboardKey::Left);
    if (i_state.Up) actions.insert(KeyboardKey::Up);
    if (i_state.Right) actions.insert(KeyboardKey::Right);
    if (i_state.Down) actions.insert(KeyboardKey::Down);
    if (i_state.Select) actions.insert(KeyboardKey::Select);
    if (i_state.Print) actions.insert(KeyboardKey::Print);
    if (i_state.Execute) actions.insert(KeyboardKey::Execute);
    if (i_state.PrintScreen) actions.insert(KeyboardKey::PrintScreen);
    if (i_state.Insert) actions.insert(KeyboardKey::Insert);
    if (i_state.Delete) actions.insert(KeyboardKey::Delete);
    if (i_state.Help) actions.insert(KeyboardKey::Help);
    if (i_state.D0) actions.insert(KeyboardKey::D0);
    if (i_state.D1) actions.insert(KeyboardKey::D1);
    if (i_state.D2) actions.insert(KeyboardKey::D2);
    if (i_state.D3) actions.insert(KeyboardKey::D3);
    if (i_state.D4) actions.insert(KeyboardKey::D4);
    if (i_state.D5) actions.insert(KeyboardKey::D5);
    if (i_state.D6) actions.insert(KeyboardKey::D6);
    if (i_state.D7) actions.insert(KeyboardKey::D7);
    if (i_state.D8) actions.insert(KeyboardKey::D8);
    if (i_state.D9) actions.insert(KeyboardKey::D9);
    if (i_state.A) actions.insert(KeyboardKey::A);
    if (i_state.B) actions.insert(KeyboardKey::B);
    if (i_state.C) actions.insert(KeyboardKey::C);
    if (i_state.D) actions.insert(KeyboardKey::D);
    if (i_state.E) actions.insert(KeyboardKey::E);
    if (i_state.F) actions.insert(KeyboardKey::F);
    if (i_state.G) actions.insert(KeyboardKey::G);
    if (i_state.H) actions.insert(KeyboardKey::H);
    if (i_state.I) actions.insert(KeyboardKey::I);
    if (i_state.J) actions.insert(KeyboardKey::J);
    if (i_state.K) actions.insert(KeyboardKey::K);
    if (i_state.L) actions.insert(KeyboardKey::L);
    if (i_state.M) actions.insert(KeyboardKey::M);
    if (i_state.N) actions.insert(KeyboardKey::N);
    if (i_state.O) actions.insert(KeyboardKey::O);
    if (i_state.P) actions.insert(KeyboardKey::P);
    if (i_state.Q) actions.insert(KeyboardKey::Q);
    if (i_state.R) actions.insert(KeyboardKey::R);
    if (i_state.S) actions.insert(KeyboardKey::S);
    if (i_state.T) actions.insert(KeyboardKey::T);
    if (i_state.U) actions.insert(KeyboardKey::U);
    if (i_state.V) actions.insert(KeyboardKey::V);
    if (i_state.W) actions.insert(KeyboardKey::W);
    if (i_state.X) actions.insert(KeyboardKey::X);
    if (i_state.Y) actions.insert(KeyboardKey::Y);
    if (i_state.Z) actions.insert(KeyboardKey::Z);
    if (i_state.LeftWindows) actions.insert(KeyboardKey::LeftWindows);
    if (i_state.RightWindows) actions.insert(KeyboardKey::RightWindows);
    if (i_state.Apps) actions.insert(KeyboardKey::Apps);
    if (i_state.Sleep) actions.insert(KeyboardKey::Sleep);
    if (i_state.NumPad0) actions.insert(KeyboardKey::NumPad0);
    if (i_state.NumPad1) actions.insert(KeyboardKey::NumPad1);
    if (i_state.NumPad2) actions.insert(KeyboardKey::NumPad2);
    if (i_state.NumPad3) actions.insert(KeyboardKey::NumPad3);
    if (i_state.NumPad4) actions.insert(KeyboardKey::NumPad4);
    if (i_state.NumPad5) actions.insert(KeyboardKey::NumPad5);
    if (i_state.NumPad6) actions.insert(KeyboardKey::NumPad6);
    if (i_state.NumPad7) actions.insert(KeyboardKey::NumPad7);
    if (i_state.NumPad8) actions.insert(KeyboardKey::NumPad8);
    if (i_state.NumPad9) actions.insert(KeyboardKey::NumPad9);
    if (i_state.Multiply) actions.insert(KeyboardKey::Multiply);
    if (i_state.Add) actions.insert(KeyboardKey::Add);
    if (i_state.Separator) actions.insert(KeyboardKey::Separator);
    if (i_state.Subtract) actions.insert(KeyboardKey::Subtract);
    if (i_state.Decimal) actions.insert(KeyboardKey::Decimal);
    if (i_state.Divide) actions.insert(KeyboardKey::Divide);
    if (i_state.F1) actions.insert(KeyboardKey::F1);
    if (i_state.F2) actions.insert(KeyboardKey::F2);
    if (i_state.F3) actions.insert(KeyboardKey::F3);
    if (i_state.F4) actions.insert(KeyboardKey::F4);
    if (i_state.F5) actions.insert(KeyboardKey::F5);
    if (i_state.F6) actions.insert(KeyboardKey::F6);
    if (i_state.F7) actions.insert(KeyboardKey::F7);
    if (i_state.F8) actions.insert(KeyboardKey::F8);
    if (i_state.F9) actions.insert(KeyboardKey::F9);
    if (i_state.F10) actions.insert(KeyboardKey::F10);
    if (i_state.F11) actions.insert(KeyboardKey::F11);
    if (i_state.F12) actions.insert(KeyboardKey::F12);
    if (i_state.F13) actions.insert(KeyboardKey::F13);
    if (i_state.F14) actions.insert(KeyboardKey::F14);
    if (i_state.F15) actions.insert(KeyboardKey::F15);
    if (i_state.F16) actions.insert(KeyboardKey::F16);
    if (i_state.F17) actions.insert(KeyboardKey::F17);
    if (i_state.F18) actions.insert(KeyboardKey::F18);
    if (i_state.F19) actions.insert(KeyboardKey::F19);
    if (i_state.F20) actions.insert(KeyboardKey::F20);
    if (i_state.F21) actions.insert(KeyboardKey::F21);
    if (i_state.F22) actions.insert(KeyboardKey::F22);
    if (i_state.F23) actions.insert(KeyboardKey::F23);
    if (i_state.F24) actions.insert(KeyboardKey::F24);
    if (i_state.NumLock) actions.insert(KeyboardKey::NumLock);
    if (i_state.Scroll) actions.insert(KeyboardKey::Scroll);
    if (i_state.LeftShift) actions.insert(KeyboardKey::LeftShift);
    if (i_state.RightShift) actions.insert(KeyboardKey::RightShift);
    if (i_state.LeftControl) actions.insert(KeyboardKey::LeftControl);
    if (i_state.RightControl) actions.insert(KeyboardKey::RightControl);
    if (i_state.LeftAlt) actions.insert(KeyboardKey::LeftAlt);
    if (i_state.RightAlt) actions.insert(KeyboardKey::RightAlt);
    if (i_state.BrowserBack) actions.insert(KeyboardKey::BrowserBack);
    if (i_state.BrowserForward) actions.insert(KeyboardKey::BrowserForward);
    if (i_state.BrowserRefresh) actions.insert(KeyboardKey::BrowserRefresh);
    if (i_state.BrowserStop) actions.insert(KeyboardKey::BrowserStop);
    if (i_state.BrowserSearch) actions.insert(KeyboardKey::BrowserSearch);
    if (i_state.BrowserFavorites) actions.insert(KeyboardKey::BrowserFavorites);
    if (i_state.BrowserHome) actions.insert(KeyboardKey::BrowserHome);
    if (i_state.VolumeMute) actions.insert(KeyboardKey::VolumeMute);
    if (i_state.VolumeDown) actions.insert(KeyboardKey::VolumeDown);
    if (i_state.VolumeUp) actions.insert(KeyboardKey::VolumeUp);
    if (i_state.MediaNextTrack) actions.insert(KeyboardKey::MediaNextTrack);
    if (i_state.MediaPreviousTrack) actions.insert(KeyboardKey::MediaPreviousTrack);
    if (i_state.MediaStop) actions.insert(KeyboardKey::MediaStop);
    if (i_state.MediaPlayPause) actions.insert(KeyboardKey::MediaPlayPause);
    if (i_state.LaunchMail) actions.insert(KeyboardKey::LaunchMail);
    if (i_state.SelectMedia) actions.insert(KeyboardKey::SelectMedia);
    if (i_state.LaunchApplication1) actions.insert(KeyboardKey::LaunchApplication1);
    if (i_state.LaunchApplication2) actions.insert(KeyboardKey::LaunchApplication2);
    if (i_state.OemSemicolon) actions.insert(KeyboardKey::OemSemicolon);
    if (i_state.OemPlus) actions.insert(KeyboardKey::OemPlus);
    if (i_state.OemComma) actions.insert(KeyboardKey::OemComma);
    if (i_state.OemMinus) actions.insert(KeyboardKey::OemMinus);
    if (i_state.OemPeriod) actions.insert(KeyboardKey::OemPeriod);
    if (i_state.OemQuestion) actions.insert(KeyboardKey::OemQuestion);
    if (i_state.OemTilde) actions.insert(KeyboardKey::OemTilde);
    if (i_state.OemOpenBrackets) actions.insert(KeyboardKey::OemOpenBrackets);
    if (i_state.OemPipe) actions.insert(KeyboardKey::OemPipe);
    if (i_state.OemCloseBrackets) actions.insert(KeyboardKey::OemCloseBrackets);
    if (i_state.OemQuotes) actions.insert(KeyboardKey::OemQuotes);
    if (i_state.Oem8) actions.insert(KeyboardKey::Oem8);
    if (i_state.OemBackslash) actions.insert(KeyboardKey::OemBackslash);
    if (i_state.ProcessKey) actions.insert(KeyboardKey::ProcessKey);
    if (i_state.OemCopy) actions.insert(KeyboardKey::OemCopy);
    if (i_state.OemAuto) actions.insert(KeyboardKey::OemAuto);
    if (i_state.OemEnlW) actions.insert(KeyboardKey::OemEnlW);
    if (i_state.Attn) actions.insert(KeyboardKey::Attn);
    if (i_state.Crsel) actions.insert(KeyboardKey::Crsel);
    if (i_state.Exsel) actions.insert(KeyboardKey::Exsel);
    if (i_state.EraseEof) actions.insert(KeyboardKey::EraseEof);
    if (i_state.Play) actions.insert(KeyboardKey::Play);
    if (i_state.Zoom) actions.insert(KeyboardKey::Zoom);
    if (i_state.Pa1) actions.insert(KeyboardKey::Pa1);
    if (i_state.OemClear) actions.insert(KeyboardKey::OemClear);

    return actions;
  }

} // ns Dx
